[CmdletBinding()]
param(
    [ValidateSet("Debug", "Release")]
    [string]$Configuration = "Debug"
)

$ErrorActionPreference = "Stop"

$workspace = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $workspace

$resetScript = Join-Path $workspace "tools\reset_registration.ps1"
$msbuild = & (Join-Path $workspace "tools\find_vs_msbuild.ps1")
$solution = Join-Path $workspace "ExcelCalibrationAddin.sln"
$manifest = Join-Path $workspace "src\ExcelCalibrationAddin.Vsto\bin\$Configuration\ExcelStandaloneComAddin.Vsto.vsto"
$buildStartedUtc = [DateTime]::UtcNow

if (!$msbuild -or !(Test-Path $msbuild)) {
    throw "Visual Studio MSBuild not found. Install Visual Studio 2022 with Office/SharePoint development tools."
}

Write-Host "== Close Excel and remove previous add-in registrations =="
& powershell -ExecutionPolicy Bypass -File $resetScript
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

Write-Host "== Clean stale VSTO build outputs =="
# reset_registration.ps1 has already removed VSTO metadata. Skipping VSTO's second
# unregister avoids its FileNotFoundException while preserving the normal Clean targets.
& $msbuild $solution /t:Clean /p:Configuration=$Configuration /p:Platform="Any CPU" /p:VSTOCleanDependsOn=
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

Write-Host "== Restore VSTO solution =="
& $msbuild $solution /t:Restore /p:Configuration=$Configuration /p:Platform="Any CPU"
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

Write-Host "== Build latest VSTO add-in =="
& $msbuild $solution /t:Build /p:Configuration=$Configuration /p:Platform="Any CPU"
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

if (!(Test-Path -LiteralPath $manifest)) {
    throw "VSTO manifest not found after build: $manifest"
}

$manifestInfo = Get-Item -LiteralPath $manifest
if ($manifestInfo.LastWriteTimeUtc -lt $buildStartedUtc) {
    throw "VSTO manifest was not regenerated by this build: $manifest"
}

Write-Host "Latest VSTO manifest built: $($manifestInfo.FullName)"
